[package]
name = "z_index_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-web-actors = "4.0"
actix = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5"
walkdir = "2.3"
notify = "4.0"